name: TiaCustomOnline
main: net.ttfl.code.paper.TiaCustomOnline
version: '${version}'
author: TiaTheFairyLand
api-version: 1.20
softdepend: [PlaceholderAPI]

commands:
  tiacustomonline:
    description: tiacustomonline
    usage: /tiacustomonline
    aliases: [tco]