name: TiaCustomOnline
main: net.ttfl.code.TiaCustomOnline
version: '${version}'
api-version: 1.20
softdepend: [PlaceholderAPI]

commands:
  tiacustomonline:
    description: tiacustomonline
    usage: /tiacustomonline
    aliases: [tco]